### ISSUE TITLE
UI Bug (b27): Web viewer intermittently refuses to scroll, and reacts like I'm trying to move the entire bounding box

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#24]
SEE ATTACHED SCREEN RECORDING.

### Brief description of the issue:
Sometimes the web viewer responds to a finger drag by not scrolling the contents of the frame, but the invisible bounding box itself.  A gray box appears at the top and bottom as I try to go 'out of bounds.'  After repeating the same action a few times, I can eventually succeed in scrolling the contents of the window as expected.

### Steps to reproduce: Intermittent.  
1. You can be logged in or anonymous for this test.
2. Find a song and scroll to the comments. 
3. Sort by oldest to find an account that has a long history of ratings and comments.
4. Open that user's profile.
5. Open each section of their profile.
6. Try to scroll with your finger in the Comments or Ratings section.
7. Sometimes you'll see a grey box on the top and bottom of the screen but the contents remain in a fixed position.  Other times the contents of that section will scroll as expected within their sections.
8. Go back to the song page and try scrolling again. Do you observe the same unpredictable behavior as on the profile page?

### Expected result: 
I expect the area to always scroll the contents within that frame, and if I try to scroll out of bounds for that content, the content should follow my finger.  

### Actual result: 
Unexpected scrolling behavior.  A bounding box is covering up the content, as if the box itself is following my finger, not the content within.

### Where did you see it? 
Build 27, iPhone 12 Pro, iOS 15.7.1

**Comment by bradtchapman** [comment]
Screen recording attached (had to recompress it from 200MB down to 15 MB).

https://user-images.githubusercontent.com/32527656/215923866-d51d2d32-32cb-4d58-8acf-ce2350e415be.mp4

**Comment by donshefer** [comment]
@bradtchapman I followed the steps but I was not able to see any incorrect behavior.
@RPNate1 Can you test and confirm, please?

**Comment by bradtchapman** [comment]
Questions/

1. Are you testing on a real device or Xcode simulator?

2. Are you able to test on iOS 15 vs 16?

3. What screen size?  I am seeing this on an iPhone 12 Pro.

**Comment by RPNate1** [comment]
I tested and once I tried to return to song view/info mode from profile, I couldn't return to song/info. I was locked in the user profile. Scrolling all seemed to work until then.

**Comment by donshefer** [comment]
Should be fixed in build 30.

**Comment by RPNate1** [comment]
We had an issue pop up with scrolling on the main site with this today. I couldn't always replicate. Jarred is working on a fix.

**Comment by RPNate1** [comment]
This appears to be fixed in b30

**Comment by bradtchapman** [comment]
NOT FIXED.  Please reopen.  I am driving in my car, but I was able to reproduce it in just a few seconds at a stoplight.

**Comment by bradtchapman** [comment]
Steps to reproduce (if no physical device, use Safari's responsive design set to iPhone 12 Pro)

1. Kill / relaunch the app.
2. Start playing any stream.  I did Rock Mix.
3. Open the history viewer. 
4. Pick any previous song (I chose "Devil Inside" by INXS)
5. Scroll to user comments.
6. Pick any user name.
7. Try to scroll with a finger. 
8. The contents will not move, but a medium gray bounding box will appear at the top or bottom, with elasticity depending on how hard you "pull.". If you pull down, it will cover up the "Profile" band.  If you pull up, it will cover Song Ratings, Play History, etc.

**Comment by RPNate1** [comment]
I tried to recreate. I was able to get the "bounding boxes" with elasticity, but I was still able to scroll the content. I only got the boxes if I tried to scroll outside the scrollable area. It did briefly lockout scrolling but I tapped within the scrollable area and scrolling was restored.

**Comment by RPNate1** [comment]
@donshefer take a look at this one and see if we can curb that issue.

**Comment by RPNate1** [comment]
I still see the same thing I reported above. I wonder if the tapping to scroll has something to do with the content containers and how they work in the webview. This is the only place this happens and is the only place we have those. The behavior, while a little strange, is easily overcome with a simple click of the content if the scrolling locks. @jarro @donshefer what do you think is happening here?

**Comment by bradtchapman** [comment]
@RPNate1 @jarro @donshefer : I can *only* reproduce this issue now on the **iPhone 12 Pro**.  I bet it has something to do with that specific screen size and how the CSS .  It doesn't happen on the small iPhone SE, and not on the iPad mini.

All I have to do is put my finger on one of the headers (Profile, Song Ratings, etc) and pull up or down.

**Comment by donshefer** [comment]
I've tried and I am not seeing this. @RPNate1, can we get on a call and you show me?

**Comment by bradtchapman** [comment]
Would you like to get on a Zoom so I can show you, @donshefer ?  I'm available now.  I have an additional detail: if I try to tap & scroll on the headers BEFORE the "Back" navigator element appears, the frame is locked correctly.  But it's only for that brief moment before "Back" appears.  Once it's there, I can create the rolling black box.

**Comment by donshefer** [comment]
@bradtchapman I took another look at the video and it seems to be working as I would expect it to. What we have is a scroll view inside a scroll view, which is not uncommon. When you get to the top or bottom, or there is no content to scroll, like on the profile, it indicates that by pulling down the edge a little ways like shown in the video. 
The only time I see it lock for a moment is while it is still loading. It locks the scrolling until to page is loaded.
Unless I'm missing something, it appear to be working as expected.

**Comment by jarro** [comment]
The huge scrollbar is another indicator that the view hasn't loaded yet.    If you can't scroll and the scrollbar is small,  that would probably be an issue.

**Comment by bradtchapman** [comment]
@RPNate1 : I notice you closed this.  Was it fixed in a recent build, or has this been moved to Trello for refinement on the web interface?

**Comment by jarro** [comment]
On closer inspection you should be able to scroll those comments into view. 
Seems like there is a bit of a delay in the site updating the scrollability.   Not sure there is anything to be done about that since it seems to clear up once it finishes loading.   Should probably just ignore it for now.
